Organizations:

  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererOrg
    MSPDir: crypto-config/ordererOrganizations/mobileid.com/msp

  - &VerifierOrg
    Name: VerifierOrg
    ID: VerifierOrg
    MSPDir: crypto-config/peerOrganizations/verifier.mobileid.com/msp
    AnchorPeers:
      - Host: peer0.verifier.mobileid.com
        Port: 7051
      
  - &HostOrg
    Name: HostOrg
    ID: HostOrg
    MSPDir: crypto-config/peerOrganizations/host.mobileid.com/msp
    AnchorPeers:
      - Host: peer0.host.mobileid.com
        Port: 7051

Orderer : &OrdererDefaults
  OrdererType: solo # 추후 raft로 변경
  Addresses: orderer.mobileid.com:7000
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Kafka:
    Brokers:
      - 127.0.0.1:9092
  Organizations:

Application: &ApplicationDefaults
  Organizations:

Profiles:

  OrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      SampleConsortium:
        Organizations:
          - *VerifierOrg
          - *HostOrg
  
  Channel1:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *VerifierOrg
        - *HostOrg